name: Roslyn Fork CI

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
    - name: Restore NuGet packages
      run: dotnet restore
      shell: pwsh # Explicitly set for PowerShell
run: |
        dotnet build --no-restore --configuration Release --verbosity normal *>&1 | Set-Content -Path build_errors.log
      # Roslyn's restore might be different, but this is a standard starting point
      run: dotnet build --no-restore --configuration Release --verbosity normal *>&1 | Set-Content -Path build_errors.log

    - name: Build Solution
      shell: pwsh
      continue-on-error: true # Allow tests to run even if build fails
      run: dotnet test --no-build --configuration Release --verbosity normal *>&1 | Set-Content -Path test_failures.log
        dotnet test --no-build --configuration Release --verbosity normal *>&1 | Set-Content -Path test_failures.log
    - name: Run Tests
      # Output to a file for later summary
      run: dotnet test --no-build --configuration Release --verbosity normal > test_failures.log 2>&1
      shell: pwsh
      continue-on-error: true # Allow post-test steps even if tests fail

    - name: Display Build Failures (Summary)
      if: failure() || success() # Always run to show status
      run: |
        Write-Host "--- Build Summary ---"
        Get-Content build_errors.log | Select-String -Pattern "error|fail" -CaseSensitive | Out-String | Write-Host
        Write-Host "---------------------"
      shell: pwsh

    - name: Display Test Failures (Summary)
      if: failure() || success() # Always run to show status
      run: |
        Write-Host "--- Test Summary ---"
        Get-Content test_failures.log | Select-String -Pattern "Fail" | Out-String | Write-Host
        Write-Host "--------------------"
      shell: pwsh

    - name: Upload Build and Test Logs as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ci-summary-logs
        path: |
          build_errors.log
          test_failures.log
        retention-days: 1